// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package binos.yarn;

public final class MsConnProto {
  private MsConnProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NullRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string req = 1;
    boolean hasReq();
    String getReq();
  }
  public static final class NullRequest extends
      com.google.protobuf.GeneratedMessage
      implements NullRequestOrBuilder {
    // Use NullRequest.newBuilder() to construct.
    private NullRequest(Builder builder) {
      super(builder);
    }
    private NullRequest(boolean noInit) {}
    
    private static final NullRequest defaultInstance;
    public static NullRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public NullRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return binos.yarn.MsConnProto.internal_static_binos_yarn_NullRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return binos.yarn.MsConnProto.internal_static_binos_yarn_NullRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string req = 1;
    public static final int REQ_FIELD_NUMBER = 1;
    private java.lang.Object req_;
    public boolean hasReq() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getReq() {
      java.lang.Object ref = req_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          req_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getReqBytes() {
      java.lang.Object ref = req_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        req_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      req_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getReqBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getReqBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof binos.yarn.MsConnProto.NullRequest)) {
        return super.equals(obj);
      }
      binos.yarn.MsConnProto.NullRequest other = (binos.yarn.MsConnProto.NullRequest) obj;
      
      boolean result = true;
      result = result && (hasReq() == other.hasReq());
      if (hasReq()) {
        result = result && getReq()
            .equals(other.getReq());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }
    
    @java.lang.Override
    public int hashCode() {
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasReq()) {
        hash = (37 * hash) + REQ_FIELD_NUMBER;
        hash = (53 * hash) + getReq().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      return hash;
    }
    
    public static binos.yarn.MsConnProto.NullRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static binos.yarn.MsConnProto.NullRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static binos.yarn.MsConnProto.NullRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static binos.yarn.MsConnProto.NullRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static binos.yarn.MsConnProto.NullRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static binos.yarn.MsConnProto.NullRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static binos.yarn.MsConnProto.NullRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static binos.yarn.MsConnProto.NullRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static binos.yarn.MsConnProto.NullRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static binos.yarn.MsConnProto.NullRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(binos.yarn.MsConnProto.NullRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements binos.yarn.MsConnProto.NullRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return binos.yarn.MsConnProto.internal_static_binos_yarn_NullRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return binos.yarn.MsConnProto.internal_static_binos_yarn_NullRequest_fieldAccessorTable;
      }
      
      // Construct using binos.yarn.MsConnProto.NullRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        req_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return binos.yarn.MsConnProto.NullRequest.getDescriptor();
      }
      
      public binos.yarn.MsConnProto.NullRequest getDefaultInstanceForType() {
        return binos.yarn.MsConnProto.NullRequest.getDefaultInstance();
      }
      
      public binos.yarn.MsConnProto.NullRequest build() {
        binos.yarn.MsConnProto.NullRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private binos.yarn.MsConnProto.NullRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        binos.yarn.MsConnProto.NullRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public binos.yarn.MsConnProto.NullRequest buildPartial() {
        binos.yarn.MsConnProto.NullRequest result = new binos.yarn.MsConnProto.NullRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.req_ = req_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof binos.yarn.MsConnProto.NullRequest) {
          return mergeFrom((binos.yarn.MsConnProto.NullRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(binos.yarn.MsConnProto.NullRequest other) {
        if (other == binos.yarn.MsConnProto.NullRequest.getDefaultInstance()) return this;
        if (other.hasReq()) {
          setReq(other.getReq());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              req_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string req = 1;
      private java.lang.Object req_ = "";
      public boolean hasReq() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getReq() {
        java.lang.Object ref = req_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          req_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setReq(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        req_ = value;
        onChanged();
        return this;
      }
      public Builder clearReq() {
        bitField0_ = (bitField0_ & ~0x00000001);
        req_ = getDefaultInstance().getReq();
        onChanged();
        return this;
      }
      void setReq(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        req_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:binos.yarn.NullRequest)
    }
    
    static {
      defaultInstance = new NullRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:binos.yarn.NullRequest)
  }
  
  public interface NullResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string resp = 1;
    boolean hasResp();
    String getResp();
  }
  public static final class NullResponse extends
      com.google.protobuf.GeneratedMessage
      implements NullResponseOrBuilder {
    // Use NullResponse.newBuilder() to construct.
    private NullResponse(Builder builder) {
      super(builder);
    }
    private NullResponse(boolean noInit) {}
    
    private static final NullResponse defaultInstance;
    public static NullResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public NullResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return binos.yarn.MsConnProto.internal_static_binos_yarn_NullResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return binos.yarn.MsConnProto.internal_static_binos_yarn_NullResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string resp = 1;
    public static final int RESP_FIELD_NUMBER = 1;
    private java.lang.Object resp_;
    public boolean hasResp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getResp() {
      java.lang.Object ref = resp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          resp_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRespBytes() {
      java.lang.Object ref = resp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        resp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      resp_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRespBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRespBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof binos.yarn.MsConnProto.NullResponse)) {
        return super.equals(obj);
      }
      binos.yarn.MsConnProto.NullResponse other = (binos.yarn.MsConnProto.NullResponse) obj;
      
      boolean result = true;
      result = result && (hasResp() == other.hasResp());
      if (hasResp()) {
        result = result && getResp()
            .equals(other.getResp());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }
    
    @java.lang.Override
    public int hashCode() {
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasResp()) {
        hash = (37 * hash) + RESP_FIELD_NUMBER;
        hash = (53 * hash) + getResp().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      return hash;
    }
    
    public static binos.yarn.MsConnProto.NullResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static binos.yarn.MsConnProto.NullResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static binos.yarn.MsConnProto.NullResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static binos.yarn.MsConnProto.NullResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static binos.yarn.MsConnProto.NullResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static binos.yarn.MsConnProto.NullResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static binos.yarn.MsConnProto.NullResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static binos.yarn.MsConnProto.NullResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static binos.yarn.MsConnProto.NullResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static binos.yarn.MsConnProto.NullResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(binos.yarn.MsConnProto.NullResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements binos.yarn.MsConnProto.NullResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return binos.yarn.MsConnProto.internal_static_binos_yarn_NullResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return binos.yarn.MsConnProto.internal_static_binos_yarn_NullResponse_fieldAccessorTable;
      }
      
      // Construct using binos.yarn.MsConnProto.NullResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        resp_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return binos.yarn.MsConnProto.NullResponse.getDescriptor();
      }
      
      public binos.yarn.MsConnProto.NullResponse getDefaultInstanceForType() {
        return binos.yarn.MsConnProto.NullResponse.getDefaultInstance();
      }
      
      public binos.yarn.MsConnProto.NullResponse build() {
        binos.yarn.MsConnProto.NullResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private binos.yarn.MsConnProto.NullResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        binos.yarn.MsConnProto.NullResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public binos.yarn.MsConnProto.NullResponse buildPartial() {
        binos.yarn.MsConnProto.NullResponse result = new binos.yarn.MsConnProto.NullResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resp_ = resp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof binos.yarn.MsConnProto.NullResponse) {
          return mergeFrom((binos.yarn.MsConnProto.NullResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(binos.yarn.MsConnProto.NullResponse other) {
        if (other == binos.yarn.MsConnProto.NullResponse.getDefaultInstance()) return this;
        if (other.hasResp()) {
          setResp(other.getResp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              resp_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string resp = 1;
      private java.lang.Object resp_ = "";
      public boolean hasResp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getResp() {
        java.lang.Object ref = resp_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          resp_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setResp(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        resp_ = value;
        onChanged();
        return this;
      }
      public Builder clearResp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resp_ = getDefaultInstance().getResp();
        onChanged();
        return this;
      }
      void setResp(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        resp_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:binos.yarn.NullResponse)
    }
    
    static {
      defaultInstance = new NullResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:binos.yarn.NullResponse)
  }
  
  public interface TaskAmountInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 wationgJobNum = 1;
    boolean hasWationgJobNum();
    int getWationgJobNum();
    
    // required int32 watingTaskNum = 2;
    boolean hasWatingTaskNum();
    int getWatingTaskNum();
    
    // required int32 averageTasksNumOneJob = 3;
    boolean hasAverageTasksNumOneJob();
    int getAverageTasksNumOneJob();
  }
  public static final class TaskAmountInfo extends
      com.google.protobuf.GeneratedMessage
      implements TaskAmountInfoOrBuilder {
    // Use TaskAmountInfo.newBuilder() to construct.
    private TaskAmountInfo(Builder builder) {
      super(builder);
    }
    private TaskAmountInfo(boolean noInit) {}
    
    private static final TaskAmountInfo defaultInstance;
    public static TaskAmountInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public TaskAmountInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return binos.yarn.MsConnProto.internal_static_binos_yarn_TaskAmountInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return binos.yarn.MsConnProto.internal_static_binos_yarn_TaskAmountInfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 wationgJobNum = 1;
    public static final int WATIONGJOBNUM_FIELD_NUMBER = 1;
    private int wationgJobNum_;
    public boolean hasWationgJobNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getWationgJobNum() {
      return wationgJobNum_;
    }
    
    // required int32 watingTaskNum = 2;
    public static final int WATINGTASKNUM_FIELD_NUMBER = 2;
    private int watingTaskNum_;
    public boolean hasWatingTaskNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getWatingTaskNum() {
      return watingTaskNum_;
    }
    
    // required int32 averageTasksNumOneJob = 3;
    public static final int AVERAGETASKSNUMONEJOB_FIELD_NUMBER = 3;
    private int averageTasksNumOneJob_;
    public boolean hasAverageTasksNumOneJob() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getAverageTasksNumOneJob() {
      return averageTasksNumOneJob_;
    }
    
    private void initFields() {
      wationgJobNum_ = 0;
      watingTaskNum_ = 0;
      averageTasksNumOneJob_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasWationgJobNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWatingTaskNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAverageTasksNumOneJob()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, wationgJobNum_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, watingTaskNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, averageTasksNumOneJob_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, wationgJobNum_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, watingTaskNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, averageTasksNumOneJob_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof binos.yarn.MsConnProto.TaskAmountInfo)) {
        return super.equals(obj);
      }
      binos.yarn.MsConnProto.TaskAmountInfo other = (binos.yarn.MsConnProto.TaskAmountInfo) obj;
      
      boolean result = true;
      result = result && (hasWationgJobNum() == other.hasWationgJobNum());
      if (hasWationgJobNum()) {
        result = result && (getWationgJobNum()
            == other.getWationgJobNum());
      }
      result = result && (hasWatingTaskNum() == other.hasWatingTaskNum());
      if (hasWatingTaskNum()) {
        result = result && (getWatingTaskNum()
            == other.getWatingTaskNum());
      }
      result = result && (hasAverageTasksNumOneJob() == other.hasAverageTasksNumOneJob());
      if (hasAverageTasksNumOneJob()) {
        result = result && (getAverageTasksNumOneJob()
            == other.getAverageTasksNumOneJob());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }
    
    @java.lang.Override
    public int hashCode() {
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasWationgJobNum()) {
        hash = (37 * hash) + WATIONGJOBNUM_FIELD_NUMBER;
        hash = (53 * hash) + getWationgJobNum();
      }
      if (hasWatingTaskNum()) {
        hash = (37 * hash) + WATINGTASKNUM_FIELD_NUMBER;
        hash = (53 * hash) + getWatingTaskNum();
      }
      if (hasAverageTasksNumOneJob()) {
        hash = (37 * hash) + AVERAGETASKSNUMONEJOB_FIELD_NUMBER;
        hash = (53 * hash) + getAverageTasksNumOneJob();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      return hash;
    }
    
    public static binos.yarn.MsConnProto.TaskAmountInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static binos.yarn.MsConnProto.TaskAmountInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static binos.yarn.MsConnProto.TaskAmountInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static binos.yarn.MsConnProto.TaskAmountInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static binos.yarn.MsConnProto.TaskAmountInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static binos.yarn.MsConnProto.TaskAmountInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static binos.yarn.MsConnProto.TaskAmountInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static binos.yarn.MsConnProto.TaskAmountInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static binos.yarn.MsConnProto.TaskAmountInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static binos.yarn.MsConnProto.TaskAmountInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(binos.yarn.MsConnProto.TaskAmountInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements binos.yarn.MsConnProto.TaskAmountInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return binos.yarn.MsConnProto.internal_static_binos_yarn_TaskAmountInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return binos.yarn.MsConnProto.internal_static_binos_yarn_TaskAmountInfo_fieldAccessorTable;
      }
      
      // Construct using binos.yarn.MsConnProto.TaskAmountInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        wationgJobNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        watingTaskNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        averageTasksNumOneJob_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return binos.yarn.MsConnProto.TaskAmountInfo.getDescriptor();
      }
      
      public binos.yarn.MsConnProto.TaskAmountInfo getDefaultInstanceForType() {
        return binos.yarn.MsConnProto.TaskAmountInfo.getDefaultInstance();
      }
      
      public binos.yarn.MsConnProto.TaskAmountInfo build() {
        binos.yarn.MsConnProto.TaskAmountInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private binos.yarn.MsConnProto.TaskAmountInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        binos.yarn.MsConnProto.TaskAmountInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public binos.yarn.MsConnProto.TaskAmountInfo buildPartial() {
        binos.yarn.MsConnProto.TaskAmountInfo result = new binos.yarn.MsConnProto.TaskAmountInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.wationgJobNum_ = wationgJobNum_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.watingTaskNum_ = watingTaskNum_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.averageTasksNumOneJob_ = averageTasksNumOneJob_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof binos.yarn.MsConnProto.TaskAmountInfo) {
          return mergeFrom((binos.yarn.MsConnProto.TaskAmountInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(binos.yarn.MsConnProto.TaskAmountInfo other) {
        if (other == binos.yarn.MsConnProto.TaskAmountInfo.getDefaultInstance()) return this;
        if (other.hasWationgJobNum()) {
          setWationgJobNum(other.getWationgJobNum());
        }
        if (other.hasWatingTaskNum()) {
          setWatingTaskNum(other.getWatingTaskNum());
        }
        if (other.hasAverageTasksNumOneJob()) {
          setAverageTasksNumOneJob(other.getAverageTasksNumOneJob());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasWationgJobNum()) {
          
          return false;
        }
        if (!hasWatingTaskNum()) {
          
          return false;
        }
        if (!hasAverageTasksNumOneJob()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              wationgJobNum_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              watingTaskNum_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              averageTasksNumOneJob_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 wationgJobNum = 1;
      private int wationgJobNum_ ;
      public boolean hasWationgJobNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getWationgJobNum() {
        return wationgJobNum_;
      }
      public Builder setWationgJobNum(int value) {
        bitField0_ |= 0x00000001;
        wationgJobNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearWationgJobNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        wationgJobNum_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 watingTaskNum = 2;
      private int watingTaskNum_ ;
      public boolean hasWatingTaskNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getWatingTaskNum() {
        return watingTaskNum_;
      }
      public Builder setWatingTaskNum(int value) {
        bitField0_ |= 0x00000002;
        watingTaskNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearWatingTaskNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        watingTaskNum_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 averageTasksNumOneJob = 3;
      private int averageTasksNumOneJob_ ;
      public boolean hasAverageTasksNumOneJob() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getAverageTasksNumOneJob() {
        return averageTasksNumOneJob_;
      }
      public Builder setAverageTasksNumOneJob(int value) {
        bitField0_ |= 0x00000004;
        averageTasksNumOneJob_ = value;
        onChanged();
        return this;
      }
      public Builder clearAverageTasksNumOneJob() {
        bitField0_ = (bitField0_ & ~0x00000004);
        averageTasksNumOneJob_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:binos.yarn.TaskAmountInfo)
    }
    
    static {
      defaultInstance = new TaskAmountInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:binos.yarn.TaskAmountInfo)
  }
  
  public static abstract class TaskAmountUpdateService
      implements com.google.protobuf.Service {
    protected TaskAmountUpdateService() {}
    
    public interface Interface {
      public abstract void updateTaskAmount(
          com.google.protobuf.RpcController controller,
          binos.yarn.MsConnProto.TaskAmountInfo request,
          com.google.protobuf.RpcCallback<binos.yarn.MsConnProto.NullResponse> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new TaskAmountUpdateService() {
        @java.lang.Override
        public  void updateTaskAmount(
            com.google.protobuf.RpcController controller,
            binos.yarn.MsConnProto.TaskAmountInfo request,
            com.google.protobuf.RpcCallback<binos.yarn.MsConnProto.NullResponse> done) {
          impl.updateTaskAmount(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.updateTaskAmount(controller, (binos.yarn.MsConnProto.TaskAmountInfo)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return binos.yarn.MsConnProto.TaskAmountInfo.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return binos.yarn.MsConnProto.NullResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void updateTaskAmount(
        com.google.protobuf.RpcController controller,
        binos.yarn.MsConnProto.TaskAmountInfo request,
        com.google.protobuf.RpcCallback<binos.yarn.MsConnProto.NullResponse> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return binos.yarn.MsConnProto.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.updateTaskAmount(controller, (binos.yarn.MsConnProto.TaskAmountInfo)request,
            com.google.protobuf.RpcUtil.<binos.yarn.MsConnProto.NullResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return binos.yarn.MsConnProto.TaskAmountInfo.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return binos.yarn.MsConnProto.NullResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends binos.yarn.MsConnProto.TaskAmountUpdateService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void updateTaskAmount(
          com.google.protobuf.RpcController controller,
          binos.yarn.MsConnProto.TaskAmountInfo request,
          com.google.protobuf.RpcCallback<binos.yarn.MsConnProto.NullResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          binos.yarn.MsConnProto.NullResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            binos.yarn.MsConnProto.NullResponse.class,
            binos.yarn.MsConnProto.NullResponse.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public binos.yarn.MsConnProto.NullResponse updateTaskAmount(
          com.google.protobuf.RpcController controller,
          binos.yarn.MsConnProto.TaskAmountInfo request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public binos.yarn.MsConnProto.NullResponse updateTaskAmount(
          com.google.protobuf.RpcController controller,
          binos.yarn.MsConnProto.TaskAmountInfo request)
          throws com.google.protobuf.ServiceException {
        return (binos.yarn.MsConnProto.NullResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          binos.yarn.MsConnProto.NullResponse.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_binos_yarn_NullRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_binos_yarn_NullRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_binos_yarn_NullResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_binos_yarn_NullResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_binos_yarn_TaskAmountInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_binos_yarn_TaskAmountInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\nbinos.yarn\"\032\n\013NullRequest\022" +
      "\013\n\003req\030\001 \001(\t\"\034\n\014NullResponse\022\014\n\004resp\030\001 \001" +
      "(\t\"]\n\016TaskAmountInfo\022\025\n\rwationgJobNum\030\001 " +
      "\002(\005\022\025\n\rwatingTaskNum\030\002 \002(\005\022\035\n\025averageTas" +
      "ksNumOneJob\030\003 \002(\0052c\n\027TaskAmountUpdateSer" +
      "vice\022H\n\020updateTaskAmount\022\032.binos.yarn.Ta" +
      "skAmountInfo\032\030.binos.yarn.NullResponseB\037" +
      "\n\nbinos.yarnB\013MsConnProto\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_binos_yarn_NullRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_binos_yarn_NullRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_binos_yarn_NullRequest_descriptor,
              new java.lang.String[] { "Req", },
              binos.yarn.MsConnProto.NullRequest.class,
              binos.yarn.MsConnProto.NullRequest.Builder.class);
          internal_static_binos_yarn_NullResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_binos_yarn_NullResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_binos_yarn_NullResponse_descriptor,
              new java.lang.String[] { "Resp", },
              binos.yarn.MsConnProto.NullResponse.class,
              binos.yarn.MsConnProto.NullResponse.Builder.class);
          internal_static_binos_yarn_TaskAmountInfo_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_binos_yarn_TaskAmountInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_binos_yarn_TaskAmountInfo_descriptor,
              new java.lang.String[] { "WationgJobNum", "WatingTaskNum", "AverageTasksNumOneJob", },
              binos.yarn.MsConnProto.TaskAmountInfo.class,
              binos.yarn.MsConnProto.TaskAmountInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
